### PR TITLE
kuma-cp: SDS server should support DiscoveryRequests with an empty list of resource names

### LINKED ISSUE #328: SDS server should support DiscoveryRequests with an empty list of resource names
### Summary

* Apparently, in some situations `envoy` sends a `DiscoveryRequest` (for a `Secret`) with an empty list of resource names
* Notice that `DiscoveryRequest` has `version_info` and `response_once` set
* Similar behaviour is observed on both `envoy` `v1.11` and `v1.12-dev`

### Steps To Reproduce

1. Enable mTLS
2. Disable mTLS
3. `envoy` issues these strange requests once draining of old listeners (that had mTLS configuration) is complete

### Additional Details & Logs

```
2019-10-08T13:40:14.867Z	ERROR	sds-server	XDS stream terminated with an error	{"streamID": 4, "error": "invalid SDS request: expected exactly 1 resourceName, got 0: version_info:\"305aa07e-e9cf-11e9-b261-fe2dbdac98de\" node:<id:\"default.kuma-tcp-echo-6b6c5b5b5-st7jd.kuma-app\" cluster:\"kuma-tcp-echo.kuma-app.svc:8000\" build_version:\"e349fb6139e4b7a59a9a359be0ea45dd61e589c5/1.11.1/Clean/RELEASE/BoringSSL\" > type_url:\"type.googleapis.com/envoy.api.v2.auth.Secret\" response_nonce:\"1\" ", "errorVerbose": "invalid SDS request: expected exactly 1 resourceName, got 0: version_info:\"305aa07e-e9cf-11e9-b261-fe2dbdac98de\" node:<id:\"default.kuma-tcp-echo-6b6c5b5b5-st7jd.kuma-app\" cluster:\"kuma-tcp-echo.kuma-app.svc:8000\" build_version:\"e349fb6139e4b7a59a9a359be0ea45dd61e589c5/1.11.1/Clean/RELEASE/BoringSSL\" > type_url:\"type.googleapis.com/envoy.api.v2.auth.Secret\" response_nonce:\"1\" \ngithub.com/Kong/kuma/pkg/sds/server.(*server).validateSdsRequest\n\t/go/src/github.com/Kong/kuma/pkg/sds/server/sds.go:226\ngithub.com/Kong/kuma/pkg/sds/server.(*server).process\n\t/go/src/github.com/Kong/kuma/pkg/sds/server/sds.go:188\ngithub.com/Kong/kuma/pkg/sds/server.(*server).handler\n\t/go/src/github.com/Kong/kuma/pkg/sds/server/sds.go:267\ngithub.com/Kong/kuma/pkg/sds/server.(*server).StreamSecrets\n\t/go/src/github.com/Kong/kuma/pkg/sds/server/sds.go:275\ngithub.com/envoyproxy/go-control-plane/envoy/service/discovery/v2._SecretDiscoveryService_StreamSecrets_Handler\n\t/go/pkg/mod/github.com/envoyproxy/go-control-plane@v0.8.2/envoy/service/discovery/v2/sds.pb.go:235\ngoogle.golang.org/grpc.(*Server).processStreamingRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.22.0/server.go:1202\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.22.0/server.go:1282\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.1\n\t/go/pkg/mod/google.golang.org/grpc@v1.22.0/server.go:717\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1337"}
2019-10-08T13:40:14.867Z	ERROR	sds-server	XDS stream terminated with an error	{"streamID": 3, "error": "invalid SDS request: expected exactly 1 resourceName, got 0: version_info:\"307bc3ff-e9cf-11e9-b261-fe2dbdac98de\" node:<id:\"default.kuma-tcp-echo-6b6c5b5b5-st7jd.kuma-app\" cluster:\"kuma-tcp-echo.kuma-app.svc:8000\" build_version:\"e349fb6139e4b7a59a9a359be0ea45dd61e589c5/1.11.1/Clean/RELEASE/BoringSSL\" > type_url:\"type.googleapis.com/envoy.api.v2.auth.Secret\" response_nonce:\"1\" ", "errorVerbose": "invalid SDS request: expected exactly 1 resourceName, got 0: version_info:\"307bc3ff-e9cf-11e9-b261-fe2dbdac98de\" node:<id:\"default.kuma-tcp-echo-6b6c5b5b5-st7jd.kuma-app\" cluster:\"kuma-tcp-echo.kuma-app.svc:8000\" build_version:\"e349fb6139e4b7a59a9a359be0ea45dd61e589c5/1.11.1/Clean/RELEASE/BoringSSL\" > type_url:\"type.googleapis.com/envoy.api.v2.auth.Secret\" response_nonce:\"1\" \ngithub.com/Kong/kuma/pkg/sds/server.(*server).validateSdsRequest\n\t/go/src/github.com/Kong/kuma/pkg/sds/server/sds.go:226\ngithub.com/Kong/kuma/pkg/sds/server.(*server).process\n\t/go/src/github.com/Kong/kuma/pkg/sds/server/sds.go:188\ngithub.com/Kong/kuma/pkg/sds/server.(*server).handler\n\t/go/src/github.com/Kong/kuma/pkg/sds/server/sds.go:267\ngithub.com/Kong/kuma/pkg/sds/server.(*server).StreamSecrets\n\t/go/src/github.com/Kong/kuma/pkg/sds/server/sds.go:275\ngithub.com/envoyproxy/go-control-plane/envoy/service/discovery/v2._SecretDiscoveryService_StreamSecrets_Handler\n\t/go/pkg/mod/github.com/envoyproxy/go-control-plane@v0.8.2/envoy/service/discovery/v2/sds.pb.go:235\ngoogle.golang.org/grpc.(*Server).processStreamingRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.22.0/server.go:1202\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.22.0/server.go:1282\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.1\n\t/go/pkg/mod/google.golang.org/grpc@v1.22.0/server.go:717\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1337"}
2019-10-08T13:40:15.028Z	ERROR	sds-server	XDS stream terminated with an error	{"streamID": 2, "error": "invalid SDS request: expected exactly 1 resourceName, got 0: version_info:\"2c6015e8-e9cf-11e9-b261-fe2dbdac98de\" node:<id:\"default.kuma-tcp-echo-6b6c5b5b5-bx9m9.kuma-app\" cluster:\"kuma-tcp-echo.kuma-app.svc:8000\" build_version:\"e349fb6139e4b7a59a9a359be0ea45dd61e589c5/1.11.1/Clean/RELEASE/BoringSSL\" > type_url:\"type.googleapis.com/envoy.api.v2.auth.Secret\" response_nonce:\"1\" ", "errorVerbose": "invalid SDS request: expected exactly 1 resourceName, got 0: version_info:\"2c6015e8-e9cf-11e9-b261-fe2dbdac98de\" node:<id:\"default.kuma-tcp-echo-6b6c5b5b5-bx9m9.kuma-app\" cluster:\"kuma-tcp-echo.kuma-app.svc:8000\" build_version:\"e349fb6139e4b7a59a9a359be0ea45dd61e589c5/1.11.1/Clean/RELEASE/BoringSSL\" > type_url:\"type.googleapis.com/envoy.api.v2.auth.Secret\" response_nonce:\"1\" \ngithub.com/Kong/kuma/pkg/sds/server.(*server).validateSdsRequest\n\t/go/src/github.com/Kong/kuma/pkg/sds/server/sds.go:226\ngithub.com/Kong/kuma/pkg/sds/server.(*server).process\n\t/go/src/github.com/Kong/kuma/pkg/sds/server/sds.go:188\ngithub.com/Kong/kuma/pkg/sds/server.(*server).handler\n\t/go/src/github.com/Kong/kuma/pkg/sds/server/sds.go:267\ngithub.com/Kong/kuma/pkg/sds/server.(*server).StreamSecrets\n\t/go/src/github.com/Kong/kuma/pkg/sds/server/sds.go:275\ngithub.com/envoyproxy/go-control-plane/envoy/service/discovery/v2._SecretDiscoveryService_StreamSecrets_Handler\n\t/go/pkg/mod/github.com/envoyproxy/go-control-plane@v0.8.2/envoy/service/discovery/v2/sds.pb.go:235\ngoogle.golang.org/grpc.(*Server).processStreamingRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.22.0/server.go:1202\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.22.0/server.go:1282\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.1\n\t/go/pkg/mod/google.golang.org/grpc@v1.22.0/server.go:717\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1337"}
2019-10-08T13:40:15.028Z	ERROR	sds-server	XDS stream terminated with an error	{"streamID": 1, "error": "invalid SDS request: expected exactly 1 resourceName, got 0: version_info:\"2c70353c-e9cf-11e9-b261-fe2dbdac98de\" node:<id:\"default.kuma-tcp-echo-6b6c5b5b5-bx9m9.kuma-app\" cluster:\"kuma-tcp-echo.kuma-app.svc:8000\" build_version:\"e349fb6139e4b7a59a9a359be0ea45dd61e589c5/1.11.1/Clean/RELEASE/BoringSSL\" > type_url:\"type.googleapis.com/envoy.api.v2.auth.Secret\" response_nonce:\"1\" ", "errorVerbose": "invalid SDS request: expected exactly 1 resourceName, got 0: version_info:\"2c70353c-e9cf-11e9-b261-fe2dbdac98de\" node:<id:\"default.kuma-tcp-echo-6b6c5b5b5-bx9m9.kuma-app\" cluster:\"kuma-tcp-echo.kuma-app.svc:8000\" build_version:\"e349fb6139e4b7a59a9a359be0ea45dd61e589c5/1.11.1/Clean/RELEASE/BoringSSL\" > type_url:\"type.googleapis.com/envoy.api.v2.auth.Secret\" response_nonce:\"1\" \ngithub.com/Kong/kuma/pkg/sds/server.(*server).validateSdsRequest\n\t/go/src/github.com/Kong/kuma/pkg/sds/server/sds.go:226\ngithub.com/Kong/kuma/pkg/sds/server.(*server).process\n\t/go/src/github.com/Kong/kuma/pkg/sds/server/sds.go:188\ngithub.com/Kong/kuma/pkg/sds/server.(*server).handler\n\t/go/src/github.com/Kong/kuma/pkg/sds/server/sds.go:267\ngithub.com/Kong/kuma/pkg/sds/server.(*server).StreamSecrets\n\t/go/src/github.com/Kong/kuma/pkg/sds/server/sds.go:275\ngithub.com/envoyproxy/go-control-plane/envoy/service/discovery/v2._SecretDiscoveryService_StreamSecrets_Handler\n\t/go/pkg/mod/github.com/envoyproxy/go-control-plane@v0.8.2/envoy/service/discovery/v2/sds.pb.go:235\ngoogle.golang.org/grpc.(*Server).processStreamingRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.22.0/server.go:1202\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.22.0/server.go:1282\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.1\n\t/go/pkg/mod/google.golang.org/grpc@v1.22.0/server.go:717\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1337"}
```

### PR DESCRIPTION
**Pull request by yskopets**
### Summary

* `SDS` server should support `DiscoveryRequests` with an empty list of resource names

### Issues resolved

Fix #328

### CODE REVIEW

File: pkg/sds/server/sds.go [hunk 1]
```diff
@@ -185,6 +185,13 @@ func (s *server) process(stream stream, reqCh <-chan *envoy.DiscoveryRequest, de
 				}
 			}
 
+			if len(req.ResourceNames) == 0 {
+				// Do not respond to SDS requests with an empty list of resource names.
+				// In practice, such requests can be observed when Envoy is removing
+				// Listeners and Clusters with TLS configuration that refers to SDS.
```
Comment (jakubdyszkiewicz) [inline pkg/sds/server/sds.go]: 👍 for the comment explaining why
